const allSongs = [
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar",
    imgUrl: "imgs/abdo_1.jfif",
    audioUrl: "songs/4.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 2",
    imgUrl: "imgs/abdo_2.jfif",
    audioUrl: "songs/abdo_2.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 3",
    imgUrl: "imgs/abdo_3.jfif",
    audioUrl: "songs/abdo_3.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 4",
    imgUrl: "imgs/abdo_4.jfif",
    audioUrl: "songs/abdo_4.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 5",
    imgUrl: "imgs/abdo_5.jfif",
    audioUrl: "songs/abdo_5.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 6",
    imgUrl: "imgs/abdo-6.jfif",
    audioUrl: "songs/abdo_6.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 7",
    imgUrl: "imgs/abdo_7.jfif",
    audioUrl: "songs/arabic_1.m4a",
  },
  {
    name: "Abelelhalim Hafez",
    songName: "gabbar 8",
    imgUrl: "imgs/abdo_8.jfif",
    audioUrl: "songs/arabic_6.m4a",
  },
  {
    name: "Fairouz",
    songName: "Faiii",
    imgUrl: "imgs/F-1.jfif",
    audioUrl: "songs/fai-1.m4a",
  },
  {
    name: "Fairouz",
    songName: "Faiii 2",
    imgUrl: "imgs/F_2.jfif",
    audioUrl: "songs/fai-2.m4a",
  },
  {
    name: "Fairouz",
    songName: "Faiii 3",
    imgUrl: "imgs/F_3.jfif",
    audioUrl: "songs/fai-3.m4a",
  },
  {
    name: "Fairouz",
    songName: "Faiii 4",
    imgUrl: "imgs/F_4.jfif",
    audioUrl: "songs/arabic_7.m4a",
  },
  {
    name: "Om Kelthoom",
    songName: "Ommm",
    imgUrl: "imgs/om_1.jfif",
    audioUrl: "songs/om_1.m4a",
  },
  {
    name: "Om Kelthoom",
    songName: "Ommm 2",
    imgUrl: "imgs/om_2.jfif",
    audioUrl: "songs/om_2.m4a",
  },
  {
    name: "Om Kelthoom",
    songName: "Ommm 3",
    imgUrl: "imgs/om_3.jfif",
    audioUrl: "songs/arabic_9.m4a",
  },
  {
    name: "Om Kelthoom",
    songName: "Ommm 4",
    imgUrl: "imgs/om_4.jfif",
    audioUrl: "songs/1.m4a",
  },
  {
    name: "Om Kelthoom",
    songName: "Ommm 5",
    imgUrl: "imgs/om_5.jfif",
    audioUrl: "songs/2.m4a",
  },
  {
    name: "Om Kelthoom",
    songName: "Ommm 6",
    imgUrl: "imgs/om_6.jfif",
    audioUrl: "songs/3.m4a",
  },
  {
    name: "Romantic",
    songName: "romantic",
    imgUrl: "imgs/romantic_1.jfif",
    audioUrl: "songs/romantic_1.m4a",
  },
];
